### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by picks44** [kairosagency/GoogleAnalyticsClientBundle#2]
Hello,

I'm trying to use your bundle, but I get this error when I try to get pageviews (using your example) 

> Catchable Fatal Error: Argument 1 passed to Kairos\GoogleAnalyticsClientBundle\Consumer\Query::__construct() must be of the type array, string given, called in C:\wamp\www\DESiwid\src\Des\IwidBundle\Controller\BackController.php on line 33 and defined

I've set my profileId correctly, and filled the config fine (at least for Oauth,for gapi_id and gapi_account, I'm not sure and it's not well documented...).

Can you help ?

**Comment by t0k4rt** [comment]
Hi Vincent, 
Sorry we forgot to update the readme, 
You should construct a query using  this:

```
$query = new Query(array($container->getParameter('kairos_google_analytics_client.gapi_id')), $container->getParameter('kairos_google_analytics_client.oauth.base_url_api'));  
```

It's not very conveninent but we plan to improve that in a next version of the lib.
I've also update this page: https://github.com/kairosagency/GoogleAnalyticsClientBundle/blob/master/Resources/doc/usage.md
Hope it will help !

**Comment by picks44** [comment]
OK.

I have another issue, I use `Symfony\Component\HttpFoundation\Request;` in my controller,
sio there's a conflict with your `Kairos\GoogleAnalyticsClientBundle\Consumer\Request;`

**Comment by t0k4rt** [comment]
To avoid conflict with your class name you can name your include like this:

```
use Kairos\GoogleAnalyticsClientBundle\Consumer\Request AS GARequest;
```

And then do:

```
$GARequest = new GARequest($query, $p12AuthClient);
```

This should solve your issue :smile:

**Comment by picks44** [comment]
Ah yes, of course...

**Comment by picks44** [comment]
What do I need to put in `gapi_id:` and `gapi_account:` ?
The documentation doesn't specify :)

I think there's a mix btw README.md and usage.md...

**Comment by picks44** [comment]
OK I've digged a little more and found out.
I think I'm fine now, but if I may suggest one thing, please update your doc soon :)
